### PR TITLE
Rough templates for required documents

### PR DESCRIPTION
**Pull request by ayushgoel**
Opening up a pull request for discussion. Feel free to comment.

### CODE REVIEW

**Comment by sugandha7** [comment]
For submissions, you should probably create a form in some standard template where all the categories are displayed and people can submit easily.

**Comment by ayushgoel** [comment]
@sugandha7 That would add an additional step for us as maintainers to parse the info and commit it here. That is not the way contributions on Github work (Ref: [pull-requests](https://help.github.com/articles/about-pull-requests/)).
Additionally, I would like, NOT to commit submissions in my name. 😄

**Comment by jflasher** [comment]
I like the idea of the main contribution mechanism being a pull request as it lets people get familiar with using GitHub and hopefully makes them more comfortable contributing elsewhere as well. We have a similar philosophy with https://github.com/openaq/openaq-info. That being said, you could make a little system that has them auth with GitHub, gives them a form to fill out and would create the PR with their creds and the info, but that seems hard.

**Comment by jflasher** [comment]
@ayushgoel if we rename submissions.md to contributing.md, GitHub treats it specially which is maybe what we want in this case? https://github.com/blog/1184-contributing-guidelines

Otherwise, this is a great start, 👍 from me, feel free to merge in whenever you want.

**Comment by ayushgoel** [comment]
Merging

**Pull request merged**
